#!/bin/sh
CONFFILE=/etc/miredo/miredo.conf
CHROOTOPT=""
IP="/sbin/ip"
TABLE="teredo"
RTTABLES="/etc/iproute2/rt_tables"

# Default to chroot for miredo relays, but not for clients.
if egrep -qi '^[ 	]*RelayType[ 	][ 	]*(cone|relay|restricted)[ 	]*$' "$CONFFILE"; then
    CHROOTOPT="-t /var/chroot/miredo"
elif [ -f "$RTTABLES" ] ; then
    if ! "$IP" route show table "$TABLE" >/dev/null 2>&1; then
	# Add "teredo" entry to rt_tables, if not already there
	i=0
	while [ $i -lt 252 ]; do
	    i=$((i+1))
	    if ! grep -q "^$i[ 	]" "$RTTABLES"; then
		echo "$i	$TABLE" >> "$RTTABLES"
		break
	    fi
	done
    fi
fi

exec /usr/sbin/miredo -f $CHROOTOPT
