#!/bin/sh

# Clean up files
if [ -L /run/hwrng ]; then
    DEV="$(readlink /run/hwrng)"
    rm -f /run/hwrng "/var/lock/LCK..${DEV#/dev/}"
fi

# Don't restart when device is missing or broken
# udev should restart us when device is plugged in
if [ ! -c /dev/onerng -o "x$1" = "x2" ]; then
    sv down "${PWD##*/}"
fi
