#!/bin/sh

[ -r conf ] && . ./conf

sleep 2		# wait for udev to finish
[  -c /dev/onerng ] || exit 2		# Device missing
ONERNGDEV="/dev/$(readlink /dev/onerng)"	# Use canonical name
. /usr/share/onerng/init.sh			# Init device
ln -f -s "$ONERNGDEV" /run/hwrng		# Use private link

exec chpst -b rngd-onerng rngd $RNGD_OPTS -r /run/hwrng -f
