#!/bin/sh

RUNLINK="/run/hwrng"
RNGD_SVC="rngd"

# Remove the symbolic link we made, and clean-up UUCP style lockfile
if [ -L "$RUNLINK" ]; then
    TTYNAME="$(readlink "$RUNLINK")"
    rm -f "$RUNLINK" "/var/lock/LCK..${TTYNAME#/dev/}"
fi

# Start up rngd if it appears to be wanted when the onerng service
# isn't running...
if [ -n "$RNGD_SVC" -a \
	-d "/var/service/$RNGD_SVC" -a \
	! -e "/var/service/$RNGD_SVC/down" ]
then
    sv up "$RNGD_SVC"
fi
